#!/bin/bash
# ---
# working with CI circle and publishing,
# should be imported into the main build.sh
# ---
set -e

# ---
# triggers or invoke a circle pipleline. CIRCLE_TOKEN env variable should be setup
# arg $1 - the repo slug, for example 'yakworks/gorm-tools' to call the build for that one
# --
function trigger-circle {
  curl --location --request POST \
    "https://circleci.com/api/v2/project/github/${1}/pipeline" \
    --header 'Content-Type: application/json' \
    -u "${CIRCLE_TOKEN}:"
}

# initialize circle variables
function ciInitVars {
  echo "ciInitVars"
  # for testing uncomment
  # CIRCLE_BRANCH="dev"

  echo "RELEASABLE_BRANCHES $RELEASABLE_BRANCHES"
  : ${RELEASABLE_BRANCHES:="master|release/.+"}
  echo "matchReleaseBranch $CIRCLE_BRANCH $RELEASABLE_BRANCHES"
  IS_RELEASABLE_BRANCH=$( matchReleaseBranch $CIRCLE_BRANCH $RELEASABLE_BRANCHES)
  echo "IS_RELEASABLE_BRANCH $IS_RELEASABLE_BRANCH"
  if [ $IS_RELEASABLE_BRANCH ]; then
    echo "IS_RELEASABLE_BRANCH: TRUE as CIRCLE_BRANCH : $CIRCLE_BRANCH matches RELEASABLE_BRANCHES $RELEASABLE_BRANCHES"
  fi


  CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)
  echo "CIRCLE_COMPARE_URL $CIRCLE_COMPARE_URL"
  CIRCLE_COMMIT_RANGE=$(echo "$CIRCLE_COMPARE_URL" | rev | cut -d/ -f1 | rev)
  echo "CIRCLE_COMMIT_RANGE $CIRCLE_COMMIT_RANGE"
  HAS_DOC_CHANGES=$(git diff $CIRCLE_COMMIT_RANGE --name-status | grep -E "(README\.md|mkdocs\.yml|version.properties|docs/)" || true)
  # app changes if anything other than the doc files have changed
  HAS_APP_CHANGES=$(git diff $CIRCLE_COMMIT_RANGE --name-status | grep -v -E "(README\.md|mkdocs\.yml|docs/)" || true)
  if [[ $HAS_DOC_CHANGES ]]; then
    echo "HAS_DOC_CHANGES: true"
  fi
  if [[ $HAS_APP_CHANGES ]]; then
    echo "HAS_APP_CHANGES: true"
  fi

  echo "end init"
}

# publish the docmark docs
function ciPublishDocs {
  ciInitVars
  # if [[ "$HAS_DOC_CHANGES" && ${IS_RELEASABLE_BRANCH:+1} ]]; then
  if [[ $IS_RELEASABLE_BRANCH ]]; then
    echo "docs have changes and IS_RELEASABLE_BRANCH:true ... calling publishDocs"
    publishDocs
  else
    echo "docs not modified or IS_RELEASABLE_BRANCH:false ... not publishing docs"
  fi
}

# does th logic for CI to publish the lib
function ciPublishLib {
  echo "ciPublishLib"
  ciInitVars
  if [[ "$HAS_APP_CHANGES" && $IS_RELEASABLE_BRANCH ]]; then
    echo "app has changes and IS_RELEASABLE_BRANCH:true ... calling publish"
    if [ "$snapshot" == "false" ]; then
      publishRelease
      releaseFiles $CIRCLE_BRANCH
    else
      publishSnapshot
      echo "app not modified or IS_RELEASABLE_BRANCH:false ... not publishing"
    fi
  else
    echo "app not modified or IS_RELEASABLE_BRANCH:false ... not publishing"
  fi
}
