#!/bin/bash
# -----------------
# functions to help with replacing env vars in template file
# !DEPRECATED here fror reference only
# ------------------
set -e

# ---
# quick and dirty templating. replaces a defined seat of tags in format ${VAR}
# with env vaiables from the specified source file
# $1 - the file name to process
# $2 - the env file to source
# $3 - the additional vars to pass to the env file
# ---
function apply {
  template=$(cat "${1}" | sed -e "s/\${NAME}/$NAME/g" \
    -e "s~\${DOCKER_REPO}~$DOCKER_REPO~g" \
    -e "s/\${IMAGE_TAG}/$IMAGE_TAG/g" \
    -e "s/\${DB_PORT}/$DB_PORT/g" \
    -e "s/\${ING_URL}/$ING_URL/g" \
    -e "s/\${DB_SERVICE_NAME}/$DB_SERVICE_NAME/g" \
    -e "s/\${DB_IMAGE_TAG}/$DB_IMAGE_TAG/g" \
    -e "s/\${DB_PASSWORD}/$DB_PASSWORD/g" \
    -e "s/\${PASS_VAR_NAME}/$PASS_VAR_NAME/g" \
    -e "s/\${APP_NAME}/$APP_NAME/g" \
    -e "s/\${APP_IMAGE_TAG}/$APP_IMAGE_TAG/g" \
    )
  #echo "$template"
  echo "$template" | kubectl apply -f -
}
