#!/bin/bash
#
# updates the version number in README
# $1 - the new version to replace old one with
# $2 - the file name to do the replace
function replaceVersion {
  sed -i -e "s|Version: [0-9.]*[-v]*[0-9.]*|Version: ${1}|g" $2

  # updatedContent = updatedContent.replaceFirst(/${p.name}:[\d\.]+[^"]+/, "${p.name}:$version")
  # update any dependencies for plugin style versions, ie `id "yakworks.gorm-tools" version "1.2.3"`
  # updatedContent = updatedContent.replaceFirst(/(?i)${p.name}"\sversion\s"[\d\.]+[^\s]+"/, "${p.name}\" version \"$version\"")
}

# --- boiler plate function runner, keep at end of file ------
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  export -f replaceVersion
else
  replaceVersion "${@}"
  exit ${?}
fi
