#!/bin/bash

# sets the variable value if its not already set and adds it for tracking in BUILD_VARS
# args $1 - the variable name
# args $2 - the variable value to set
function setVar {
  varName="$1"
  # varVal="$2"
  # curVal="${!varName}"
  # [[ ! ${!varName+x} ]]
  if [[ -z ${!varName} ]]; then
    # echo "curVal is empty, adding"
    eval "$varName=\"\$2\""
  fi
  addBuildVars $varName
}

# sets the variable value and overwrites what was there before
# args $1 - the variable name
# args $2 - the variable value to set
function putVar {
  # declare -g "$1"="$2" # not working in older bash 3 on mac
  eval $1=\$2
  addBuildVars $1
}


# add the variable name to the BUILD_VARS list for use later in make or in logging
# args $1 - the variables
function addBuildVars {
  for bvar in "$@"; do
    if [[ ! $BUILD_VARS == *" $bvar "* ]]; then
      # echo "adding $bvar to BUILD_VARS"
      BUILD_VARS+="$bvar "
    fi
  done
}

# helper/debug function to log out the build_vars
function log-vars {
  for varName in $BUILD_VARS; do
    echo "$varName = ${!varName}"
  done
}
