#!/bin/bash
# -----------------
# some common bash util helpers
# ------------------

# ---
# trims leading and trailing spaces from string
# $1 - the string to trim
# ---
trim() {
    local trimmed="$1"

    # Strip leading spaces.
    while [[ $trimmed == ' '* ]]; do
       trimmed="${trimmed## }"
    done
    # Strip trailing spaces.
    while [[ $trimmed == *' ' ]]; do
        trimmed="${trimmed%% }"
    done

    echo "$trimmed"
}

# build app props from list which will be in form
#  dataSource.host=mysql
#  dataSource.dbName=bar
# turned into -DdataSource.host=mysql -DdataSource.dbName=bar
# $1 - the string to convert into java props
# ---
transform_to_java_props() {
  local sysProps=""
  echo "1 $1"
  while IFS= read -r line; do
    trimLine=$(trim $line)
    # if value of $var starts with #, ignore it
    [[ $trimLine =~ ^#.* ]] && continue
    # if its empty then move on
    [[ -z "$trimLine" ]] && continue

    sysProps+="-D$trimLine "
  done <<< "$1"

  echo "$sysProps"
}

# will echo if its falsy
# to be falsy a value could be false, "false", 0, "0", unset, empty string
# usage:
#   FOO=false
#   [ $(isFalsy "$FOO") ] && echo "FOO is falsy"
function isFalsy {
  [ ! "$1" ] && echo "unsetOrEmpty"; [ "$1" = false ] && echo "isFalse"; [ "$1" = 0 ] && echo "is0"
}

# will echo if its not falsy
# usage:
#   FOO="anything not falsy"
#   [ $(isTruthy "$FOO") ] && echo "FOO is truthy"
function isTruthy {
  [ ! $(isFalsy "$1") ] && echo "isTruthy"
}
